# app custom Makefile

# Docker repo & image name without version
IMAGE    ?= gomods/athens
# Hostname for external access
APP_SITE ?= gomod.dev.lan
# Keep existing APP_ROOT files
SETUP_ROOT_OPTS = keep

# ------------------------------------------------------------------------------
# app custom config

IMAGE_VER       ?= v0.10.0

LIB_PATH        ?= Athens
DCAPE_ROOT      ?= /opt/dcape/var

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

# Relative path to library sources from DCAPE/var
LIB_PATH=$(LIB_PATH)

# Path to /opt/dcape/var. Used only outside drone
#DCAPE_ROOT=$(DCAPE_ROOT)

endef


# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif
